# Generated by Django 5.2.3 on 2025-07-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nome do Experimento"
                    ),
                ),
                (
                    "design_type",
                    models.CharField(
                        choices=[
                            ("DIC", "Delineamento Inteiramente Casualizado"),
                            ("DBC", "Delineamento em Blocos Casualizados"),
                            ("QL", "Quadrado Latino"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de Delineamento",
                    ),
                ),
                ("parameters", models.JSONField(verbose_name="Parâmetros de Entrada")),
                ("layout", models.JSONField(verbose_name="Layout do Sorteio")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
